### ISSUE TITLE
Loading configuration in the CLI and exposing as a new Lua module

### ISSUE THREAD

**Issue by drognisep** [drognisep/systest#4]
This is a two-parter:
1. We will need the CLI to load configuration information from file, in the form of key/value pairs. This should be plain text configuration information that doesn't need to be encrypted for safety (host names, port numbers, things like that). When the CLI starts up, it should load config from a default location.
2. We'll need a new Lua module created, much like the `testing` module created in #1. This should provide configuration strings to tests that can be used directly. The new module should allow referencing values in configuration by key.

**Additional context:**
- We MUST NOT store any secrets in config, that'll be a separate unit of work. We don't want to expose secrets directly to Lua, but we do for configuration.
- Think about this like an "environment" in Postman. We use that to establish host names and such for one environment, and we can have the same values referenced in any request. This means that switching to a new environment should require zero changes in tests.
- We could think about formalizing the idea of "environments." I'm not sure if there's a case where that could be a problem, so feel free to add your thoughts below.

**Comment by drognisep** [comment]
@savharter @nrtyc4 
Adding notes from our previous discussion:
- This is for "single player mode"
- Should accept JSON or YAML file formats
  - We can base this off of file extension (e.g. `*.json`, `*.yaml`, `*.yml`)
  - Eventually, we probably want an editor UI to work with this, so we'll need to think about what's easiest to work with in that context too
- Should be expected in a standard location that makes sense for each OS
- Should accept a hierarchy like this
```yaml
# this is the top level namespace, like "dwh"
namespace:
  # This is the specific component, could be swapped with environment if we want to have that parallel with Postman
  component:
    # This is the deployed environment
    environment:
      # Actual key/values pairs go here
      key: value
```
- This includes the work to expose the Lua module, so we'll need to think through the code API for referencing values through this hierarchy
